language: c
compiler: clang
dist:     trusty
sudo:     false

before_install:
  - pip install --user cpp-coveralls

script: make coverage COVFLAGS='-ftest-coverage -fprofile-arcs' OPT='-O0'

after_success:
  - coveralls
